part of s;

// Generated by flutter_l10n. Do not edit it.
class $en extends S {
  const $en();

  @override
  TextDirection get textDirection => TextDirection.ltr;

  @override
  String get more => r'more';

  @override
  String get single => r'single';

  @override
  String get alone => r'alone';

  @override
  String get together => r'together';

  @override
  String get add => r'add';

  @override
  String get reduce => r'reduce';

  @override
  String get automatic => r'automatic';

  @override
  String get manual => r'manual';

  @override
  String get month => r'month';

  @override
  String get week => r'week';
}
