part of s;

// Generated by flutter_l10n. Do not edit it.
class $zh extends S {
  const $zh();

  @override
  TextDirection get textDirection => TextDirection.ltr;

  @override
  String get more => r'多选';

  @override
  String get single => r'单选';

  @override
  String get alone => r'单独';

  @override
  String get together => r'一起';

  @override
  String get add => r'加';

  @override
  String get reduce => r'减';

  @override
  String get automatic => r'自动';

  @override
  String get manual => r'手动';

  @override
  String get month => r'月';

  @override
  String get week => r'周';
}
